name: Upload Exercises

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up s3cmd
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: linode
          region: "eu-central-1"
          access_key: ${{ secrets.LINODE_S3_ACCESS_KEY }}
          secret_key: ${{ secrets.LINODE_S3_SECRET_KEY }}

      - name: Interact with object storage
        run: |
          s3cmd sync --delete-removed --delete-after --exclude '.git/*' --exclude '.github/*' . s3://resurrectism
      - name: Get info
        run: s3cmd ws-info s3://resurrectism
